import path from "path";
import { fileURLToPath } from "url";
import { defineConfig } from "vitest/config";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    setupFiles: ["./tests/setup.ts"],
    include: ["tests/**/*.test.ts", "tests/**/*.spec.ts"],
    pool: "forks",
    maxWorkers: process.env.CI ? 2 : undefined,
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov"],
      include: ["src/**/*.ts"],
      exclude: [
        "src/index.ts",
        "src/register-aliases.ts",
        "**/index.ts",
        "src/**/types.ts",
        "src/**/Types.ts",
        "**/*.d.ts",
      ],
      thresholds: {
        lines: 65,
        functions: 68,
        branches: 55,
        statements: 65,
        "src/Utilities/ApiClient.ts": {
          lines: 85,
          functions: 85,
          branches: 75,
          statements: 85,
        },
        "src/Shared/ModalRouter.ts": {
          lines: 80,
          functions: 80,
          branches: 70,
          statements: 80,
        },
        "src/Shared/Paginator.ts": {
          lines: 75,
          functions: 75,
          branches: 65,
          statements: 75,
        },
        "src/Shared/ComponentRouter.ts": {
          lines: 75,
          functions: 75,
          branches: 65,
          statements: 75,
        },
        "src/Bootstrap.ts": {
          lines: 75,
          functions: 75,
          branches: 60,
          statements: 75,
        },
        "src/Systems/Roblox/handlers/**": {
          lines: 65,
          functions: 65,
          branches: 55,
          statements: 65,
        },
        "src/Database/User/Stores/**": {
          lines: 75,
          functions: 80,
          branches: 55,
          statements: 75,
        },
        "src/Database/UserDatabase.ts": {
          lines: 75,
          functions: 75,
          branches: 90,
          statements: 75,
        },
        "src/Database/Ticket/Stores/**": {
          lines: 60,
          functions: 60,
          branches: 40,
          statements: 60,
        },
        "src/Utilities/StaffPermissions.ts": {
          lines: 90,
          functions: 100,
          branches: 85,
          statements: 90,
        },
        "src/Commands/Middleware/CooldownMiddleware.ts": {
          lines: 65,
          functions: 100,
          branches: 65,
          statements: 65,
        },
        "src/Systems/Ticket/validation/**": {
          lines: 70,
          functions: 75,
          branches: 65,
          statements: 70,
        },
        "src/Utilities/TicketManager.ts": {
          lines: 50,
          functions: 50,
          branches: 40,
          statements: 50,
        },
        "src/Database/Server/Stores/**": {
          lines: 70,
          functions: 75,
          branches: 55,
          statements: 70,
        },
        "src/Database/ServerDatabase.ts": {
          lines: 70,
          functions: 70,
          branches: 50,
          statements: 70,
        },
        "src/Database/Moderation/Stores/**": {
          lines: 70,
          functions: 75,
          branches: 55,
          statements: 70,
        },
        "src/Systems/Economy/handlers/**": {
          lines: 48,
          functions: 30,
          branches: 40,
          statements: 47,
        },
        "src/Utilities/GuildMemberResolver.ts": {
          lines: 90,
          functions: 80,
          branches: 85,
          statements: 90,
        },
        "src/Utilities/GuildResourceLocator.ts": {
          lines: 70,
          functions: 75,
          branches: 55,
          statements: 70,
        },
        "src/Commands/Utility/Giveaway/**": {
          lines: 50,
          functions: 45,
          branches: 35,
          statements: 50,
        },
        "src/Systems/Setup/handlers/**": {
          lines: 35,
          functions: 40,
          branches: 20,
          statements: 35,
        },
        "src/Commands/Moderation/Appeal/**": {
          lines: 55,
          functions: 50,
          branches: 45,
          statements: 55,
        },
      },
    },
  },
  resolve: {
    alias: {
      "@commands": path.resolve(__dirname, "src/Commands"),
      "@commands/*": path.resolve(__dirname, "src/Commands"),
      "@systems": path.resolve(__dirname, "src/Systems"),
      "@systems/*": path.resolve(__dirname, "src/Systems"),
      "@middleware": path.resolve(__dirname, "src/Commands/Middleware"),
      "@middleware/*": path.resolve(__dirname, "src/Commands/Middleware"),
      "@bot": path.resolve(__dirname, "src/Bot"),
      "@bot/*": path.resolve(__dirname, "src/Bot"),
      "@database": path.resolve(__dirname, "src/Database"),
      "@database/*": path.resolve(__dirname, "src/Database"),
      "@utilities": path.resolve(__dirname, "src/Utilities"),
      "@utilities/*": path.resolve(__dirname, "src/Utilities"),
      "@shared": path.resolve(__dirname, "src/Shared"),
      "@shared/*": path.resolve(__dirname, "src/Shared"),
      "@responders": path.resolve(__dirname, "src/Responders"),
      "@responders/*": path.resolve(__dirname, "src/Responders"),
      "@events": path.resolve(__dirname, "src/Events"),
      "@events/*": path.resolve(__dirname, "src/Events"),
      "@config": path.resolve(__dirname, "src/Config"),
      "@config/*": path.resolve(__dirname, "src/Config"),
    },
  },
});
