import { EconomyItem } from "./types";

export const ITEM_CATALOG: EconomyItem[] = [
  {
    id: "reroll-token",
    name: "Reroll Token",
    description: "Reroll once in Rock Paper Scissors before finalizing.",
    price: 120,
    sellPrice: 60,
    rarity: "common",
    type: "consumable",
    effect: "rps_reroll",
    maxStack: 10,
  },
  {
    id: "scratch-lens",
    name: "Scratch Lens",
    description: "Reveal one extra tile in Scratch before confirming picks.",
    price: 180,
    sellPrice: 90,
    rarity: "rare",
    type: "consumable",
    effect: "scratch_reveal",
    maxStack: 10,
  },
  {
    id: "dealer-charm",
    name: "Dealer's Charm",
    description: "If the dealer beats you by 1, convert it to a push (once).",
    price: 220,
    sellPrice: 110,
    rarity: "rare",
    type: "consumable",
    effect: "blackjack_edge",
    maxStack: 5,
  },
  {
    id: "lucky-coin",
    name: "Lucky Coin",
    description: "If you lose a coin flip, reroll once automatically.",
    price: 150,
    sellPrice: 75,
    rarity: "common",
    type: "consumable",
    effect: "flip_reroll",
    maxStack: 10,
  },
  {
    id: "loaded-die",
    name: "Loaded Die",
    description: "If your dice guess is wrong, reroll once for a second shot.",
    price: 200,
    sellPrice: 100,
    rarity: "rare",
    type: "consumable",
    effect: "dice_reroll",
    maxStack: 10,
  },
  {
    id: "parachute",
    name: "Parachute",
    description: "If Crash explodes before you cash out, refund your bet.",
    price: 240,
    sellPrice: 120,
    rarity: "rare",
    type: "consumable",
    effect: "crash_insurance",
    maxStack: 5,
  },
  {
    id: "speed-spur",
    name: "Speed Spur",
    description: "Your chosen horse has a higher chance to advance each tick.",
    price: 170,
    sellPrice: 85,
    rarity: "common",
    type: "consumable",
    effect: "horse_boost",
    maxStack: 10,
  },
  {
    id: "horse-whistle",
    name: "Horse Whistle",
    description: "Gives your horse a head start of one space.",
    price: 140,
    sellPrice: 70,
    rarity: "common",
    type: "consumable",
    effect: "horse_start",
    maxStack: 10,
  },
  {
    id: "rps-shield",
    name: "RPS Shield",
    description: "Converts a loss into a draw once per game.",
    price: 160,
    sellPrice: 80,
    rarity: "common",
    type: "consumable",
    effect: "rps_shield",
    maxStack: 10,
  },
  {
    id: "flip-charm",
    name: "Flip Charm",
    description: "If you win a flip, boost payout by 50%.",
    price: 180,
    sellPrice: 90,
    rarity: "rare",
    type: "consumable",
    effect: "flip_bonus",
    maxStack: 10,
  },
  {
    id: "dice-nudge",
    name: "Dice Nudge",
    description: "If your guess is off by 1, count it as a win.",
    price: 190,
    sellPrice: 95,
    rarity: "rare",
    type: "consumable",
    effect: "dice_nudge",
    maxStack: 10,
  },
  {
    id: "crash-booster",
    name: "Crash Booster",
    description: "Cashout wins gain +15% payout.",
    price: 210,
    sellPrice: 105,
    rarity: "epic",
    type: "consumable",
    effect: "crash_bonus",
    maxStack: 5,
  },
  {
    id: "scratch-clover",
    name: "Scratch Clover",
    description: "Guarantees at least a pair; upgrades a bust to a small win.",
    price: 200,
    sellPrice: 100,
    rarity: "rare",
    type: "consumable",
    effect: "scratch_luck",
    maxStack: 10,
  },
  {
    id: "coin-guardian",
    name: "Coin Guardian",
    description: "If you lose a flip, refund the bet.",
    price: 160,
    sellPrice: 80,
    rarity: "common",
    type: "consumable",
    effect: "flip_refund",
    maxStack: 10,
  },
  {
    id: "dice-jackpot",
    name: "Dice Jackpot",
    description: "When you win a dice guess, double the payout.",
    price: 210,
    sellPrice: 105,
    rarity: "epic",
    type: "consumable",
    effect: "dice_payout",
    maxStack: 5,
  },
  {
    id: "crash-autocash",
    name: "Auto Cashout Chip",
    description: "Automatically cashes out at 2.0x if you haven't already.",
    price: 230,
    sellPrice: 115,
    rarity: "rare",
    type: "consumable",
    effect: "crash_auto",
    maxStack: 5,
  },
  {
    id: "horse-rocket",
    name: "Rocket Saddle",
    description: "Your horse gets a +2 head start at race start.",
    price: 180,
    sellPrice: 90,
    rarity: "rare",
    type: "consumable",
    effect: "horse_dash",
    maxStack: 10,
  },
  {
    id: "scratch-bonus",
    name: "Lucky Sticker",
    description: "Scratch wins pay +50%; losses refund 50% of bet.",
    price: 190,
    sellPrice: 95,
    rarity: "rare",
    type: "consumable",
    effect: "scratch_bonus",
    maxStack: 10,
  },
  {
    id: "rps-edge",
    name: "RPS Edge",
    description: "Turns your first draw into a win.",
    price: 170,
    sellPrice: 85,
    rarity: "rare",
    type: "consumable",
    effect: "rps_edge",
    maxStack: 10,
  },
  {
    id: "bj-peek",
    name: "Dealer Peek",
    description: "Reveals the dealer's hole card in blackjack.",
    price: 220,
    sellPrice: 110,
    rarity: "rare",
    type: "consumable",
    effect: "blackjack_peek",
    maxStack: 5,
  },
  {
    id: "bj-boost",
    name: "High Roller Token",
    description: "Blackjack wins pay +20% (including naturals).",
    price: 240,
    sellPrice: 120,
    rarity: "epic",
    type: "consumable",
    effect: "blackjack_boost",
    maxStack: 5,
  },
];

export const ITEM_MAP: Record<string, EconomyItem> = ITEM_CATALOG.reduce(
  (acc, item) => {
    acc[item.id] = item;
    return acc;
  },
  {} as Record<string, EconomyItem>
);

export const DEFAULT_ROTATION_IDS: string[] = ITEM_CATALOG.map(
  (item) => item.id
);

